#!/usr/bin/perl
#
#       openerror
#

print "Enter a file name -> ";
$fn = <STDIN>;
chop($fn);

print "Reading from $fn ...\n";
open(INPUTFILE, "< $fn") || die;    #  || is logical OR

while(<INPUTFILE>)
{
    print "$. $_";              #  $. is the line number
}

close INPUTFILE;
