#!/usr/bin/perl
#
#	banking2
#

open(DATABASE, "< ../../datafiles/bankingdata") || die;

while(<DATABASE>)
{
    ($name, $balance) = split;
    $accounts{$name} += $balance;
}

close DATABASE;

while(1)
{
    print "Enter name: ";
    chop($name = <STDIN>);

    last unless $name;

    if (exists($accounts{$name}))
    {
        print "$name has a balance of $accounts{$name}\n";
    }
    else
    {
        print "$name is not in the database\n";
    }
}


