#!/usr/bin/perl
#
#	relational
#

$a = 5;
$b = 10;

print $a < $b, "\n";		# prints 1
print $a lt $b, "\n";		# prints empty string

$x = $a <=> $b;			# $x = -1
$y = $a <=> $a;			# $y =  0
$z = $b <=> $a;			# $z =  1
print "$x, $y, $z\n";

$x = "hello";
$y = "zebra";
print $y cmp $x, "\n";		# prints  1

