#!/usr/bin/perl
#
#	stringops
#
while(1)
{
    print "Enter string: ";
    chomp($str = <STDIN>);
    print "Enter another: ";
    chomp($other = <STDIN>);
    $str .= $other;
    print "Concatenation is: $str\n";

    print "Enter repeat factor ";
    $factor = <STDIN>;
    $str = $str x $factor;
    print "$str\n";
}
