#!/usr/bin/perl
#
#       sum
#

while(1)
{	
    print "Enter a string: ";
    $_ = <STDIN>;
    last if ( /^quit$/i );

    $total = 0;

    while(/([+-]?\d+)/g)
    {
        $total += $1;
    }

    print "$total\n";
}

